'use client';

import { useState } from 'react';
import { ArrowRight, Bell, Camera, Check, ChevronRight, Clock3, LoaderCircle, MapPin, Search, ShieldCheck, Sparkles, Upload } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';

const matches = [
  { rank: 1, score: 94, name: '白色保温杯', place: '体育馆 · 二层看台', time: '昨天 16:20', detail: '蓝色杯盖、杯身有卡通贴纸', image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=900&q=85' },
  { rank: 2, score: 78, name: '白色运动水杯', place: '体育馆 · 羽毛球场', time: '昨天 18:05', detail: '浅蓝色旋盖、杯身无图案', image: 'https://images.unsplash.com/photo-1605714196241-00bf7a8fe7bb?auto=format&fit=crop&w=900&q=85' },
  { rank: 3, score: 62, name: '银白色随行杯', place: '南区操场', time: '9月3日 17:40', detail: '蓝色杯套、杯底有轻微划痕', image: 'https://images.unsplash.com/photo-1523362628745-0c100150b504?auto=format&fit=crop&w=900&q=85' },
];

export default function Home() {
  const [query, setQuery] = useState('我昨天体育课以后，把一个白色水杯落在体育馆了，上面有蓝色的杯盖和卡通贴纸。');
  const [searched, setSearched] = useState(true);
  const [claimOpen, setClaimOpen] = useState(false);
  const [reportOpen, setReportOpen] = useState(false);
  const [claimed, setClaimed] = useState(false);
  const [recognized, setRecognized] = useState(false);
  const [notice, setNotice] = useState('');
  function showNotice(message: string) { setNotice(message); window.setTimeout(() => setNotice(''), 2400); }
  function runSearch() { setSearched(false); window.setTimeout(() => { setSearched(true); document.getElementById('results')?.scrollIntoView({ behavior: 'smooth', block: 'start' }); }, 850); }

  return (
    <main className="min-h-screen overflow-hidden bg-background text-foreground">
      <header className="sticky top-0 z-40 border-b border-slate-200/70 bg-white/80 backdrop-blur-xl">
        <div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5 sm:px-8">
          <a href="#top" className="flex items-center gap-2.5" aria-label="拾光校园失物招领首页"><span className="grid size-9 place-items-center rounded-xl bg-[#126f77] text-white shadow-sm"><Sparkles className="size-5" /></span><span className="text-lg font-bold tracking-tight">拾光</span><span className="hidden text-xs text-slate-400 sm:inline">AI 校园失物招领</span></a>
          <nav className="hidden items-center gap-7 text-sm text-slate-600 md:flex"><a href="#search" className="font-medium text-[#126f77]">智能寻物</a><button onClick={() => setReportOpen(true)} className="transition hover:text-[#126f77]">登记失物</button><a href="#how" className="transition hover:text-[#126f77]">工作原理</a></nav>
          <div className="flex items-center gap-2"><Button onClick={() => showNotice('暂时没有新的失物消息')} variant="ghost" size="icon" aria-label="通知" className="rounded-full text-slate-500"><Bell /></Button><button onClick={() => showNotice('已登录：林同学')} className="grid size-8 place-items-center rounded-full bg-[#e6f4f1] text-xs font-bold text-[#126f77]">林</button></div>
        </div>
      </header>

      <section id="top" className="relative border-b border-slate-200/70 bg-[#f6faf9]">
        <div className="absolute inset-0 opacity-40 [background-image:radial-gradient(#7ab7ad_1px,transparent_1px)] [background-size:22px_22px]" />
        <div className="relative mx-auto grid max-w-7xl gap-10 px-5 py-14 sm:px-8 lg:grid-cols-[.9fr_1.1fr] lg:items-center lg:py-20">
          <div><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-[#b9dcd5] bg-white px-3 py-1.5 text-xs font-semibold text-[#126f77] shadow-sm"><Sparkles className="size-3.5" /> AI 正在帮全校找回遗失</div><h1 className="max-w-xl text-4xl font-bold leading-[1.12] tracking-[-0.045em] text-slate-900 sm:text-6xl">丢了东西？<br /><span className="text-[#126f77]">说出来，就能找到。</span></h1><p className="mt-5 max-w-lg text-base leading-7 text-slate-600 sm:text-lg">不用翻遍失物群，也不用填写复杂表格。AI 同时理解图片、描述、时间和地点，替你从校园失物库中找到最可能的那一件。</p><div className="mt-7 flex flex-wrap items-center gap-4 text-sm text-slate-500"><span className="flex items-center gap-1.5"><Check className="size-4 text-[#21a179]" />自然语言描述</span><span className="flex items-center gap-1.5"><Check className="size-4 text-[#21a179]" />多模态匹配</span><span className="flex items-center gap-1.5"><Check className="size-4 text-[#21a179]" />隐私领取验证</span></div></div>
          <div id="search" className="relative rounded-[28px] border border-slate-200 bg-white p-4 shadow-[0_24px_70px_rgba(25,77,75,.13)] sm:p-6"><div className="mb-4 flex items-center justify-between"><div><p className="text-sm font-bold text-slate-900">告诉 AI，你丢了什么</p><p className="mt-1 text-xs text-slate-400">像和同学说话一样描述就好</p></div><span className="flex items-center gap-1 rounded-full bg-[#eaf7f3] px-2.5 py-1 text-[11px] font-semibold text-[#13766d]"><span className="size-1.5 animate-pulse rounded-full bg-[#21a179]" /> AI 在线</span></div><div className="rounded-2xl border border-slate-200 bg-[#fbfdfd] p-2 transition focus-within:border-[#71b6aa] focus-within:ring-4 focus-within:ring-[#dff1ed]"><Textarea value={query} onChange={(e) => setQuery(e.target.value)} aria-label="描述丢失的物品" className="min-h-28 resize-none border-0 bg-transparent px-3 py-3 text-[15px] leading-6 shadow-none focus-visible:ring-0" placeholder="例如：昨天下午在体育馆丢了一个白色水杯……" /><div className="flex items-center justify-between border-t border-slate-100 px-2 pt-2"><label className="flex cursor-pointer items-center gap-1.5 rounded-lg px-2 py-1.5 text-xs text-slate-500 transition hover:bg-slate-100"><Camera className="size-4" /> 添加参考照片<input type="file" accept="image/*" className="sr-only" onChange={(e) => e.target.files?.[0] && showNotice(`已添加参考照片：${e.target.files[0].name}`)} /></label><Button onClick={runSearch} disabled={!query.trim() || !searched} className="h-10 rounded-xl bg-[#126f77] px-5 hover:bg-[#0e5960]">{searched ? <Search className="size-4" /> : <LoaderCircle className="size-4 animate-spin" />} {searched ? '帮我找找' : 'AI 匹配中'}</Button></div></div><button onClick={() => setReportOpen(true)} className="mt-5 flex w-full items-center justify-between rounded-2xl bg-[#eef7ff] p-3.5 text-left transition hover:bg-[#e4f2ff]"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-white text-[#3979a8] shadow-sm"><Camera className="size-5" /></div><div><p className="text-sm font-semibold text-slate-800">捡到了东西？</p><p className="text-xs text-slate-500">拍张照片，AI 帮你自动登记</p></div></div><ChevronRight className="size-5 text-[#3979a8]" /></button></div>
        </div>
      </section>

      <section id="results" className="mx-auto max-w-7xl scroll-mt-20 px-5 py-12 sm:px-8 sm:py-16">
        <div className="mb-7 flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><div className="flex items-center gap-2 text-sm font-semibold text-[#126f77]"><Search className="size-4" /> AI 匹配结果</div><h2 className="mt-2 text-2xl font-bold tracking-tight text-slate-900">找到 3 件疑似物品</h2><p className="mt-1.5 text-sm text-slate-500">已综合比较物品外观、文字特征、发现地点与时间</p></div><div className="flex items-center gap-2 text-xs text-slate-400"><span className="size-2 rounded-full bg-[#21a179]" /> 刚刚更新</div></div>
        <div className={`grid gap-5 transition-all duration-500 lg:grid-cols-3 ${searched ? 'translate-y-0 opacity-100' : 'translate-y-2 opacity-30'}`}>
          {matches.map((item) => <article key={item.rank} className={`group overflow-hidden rounded-3xl border bg-white transition hover:-translate-y-1 hover:shadow-xl ${item.rank === 1 ? 'border-[#8fcbbf] shadow-[0_16px_44px_rgba(29,112,103,.12)]' : 'border-slate-200 shadow-sm'}`}><div className="relative h-48 overflow-hidden bg-slate-100"><img src={item.image} alt={item.name} className="h-full w-full object-cover transition duration-500 group-hover:scale-105" /><div className="absolute inset-x-0 top-0 flex items-start justify-between p-4"><span className={`rounded-full px-3 py-1 text-xs font-bold shadow-sm backdrop-blur ${item.rank === 1 ? 'bg-[#fff4cf] text-[#8a6210]' : 'bg-white/90 text-slate-600'}`}>{item.rank === 1 ? '🥇 最可能是它' : `候选 ${item.rank}`}</span><span className="rounded-full bg-[#126f77] px-3 py-1 text-sm font-bold text-white shadow-lg">{item.score}%</span></div></div><div className="p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="text-lg font-bold text-slate-900">{item.name}</h3><p className="mt-1 text-xs font-medium text-[#178170]">匹配度 {item.score}%</p></div><div className="relative size-11 rounded-full" style={{background: `conic-gradient(#21a179 ${item.score * 3.6}deg,#e6eeec 0)`}}><span className="absolute inset-[4px] grid place-items-center rounded-full bg-white text-[10px] font-bold text-slate-600">{item.score}</span></div></div><div className="mt-4 space-y-2 text-sm text-slate-500"><p className="flex items-center gap-2"><MapPin className="size-4 text-slate-400" />{item.place}</p><p className="flex items-center gap-2"><Clock3 className="size-4 text-slate-400" />{item.time}</p></div><div className="mt-4 rounded-xl bg-slate-50 p-3 text-sm leading-6 text-slate-600"><span className="font-semibold text-slate-800">识别特征：</span>{item.detail}</div><Button onClick={() => setClaimOpen(true)} className={`mt-5 h-11 w-full rounded-xl ${item.rank === 1 ? 'bg-[#126f77] hover:bg-[#0e5960]' : 'bg-slate-900 hover:bg-slate-700'}`}>这是我的 <ArrowRight className="size-4" /></Button></div></article>)}
        </div>
      </section>

      <section id="how" className="border-y border-slate-200 bg-[#f7f9fb] py-16"><div className="mx-auto max-w-7xl px-5 sm:px-8"><div className="mx-auto max-w-2xl text-center"><p className="text-sm font-semibold text-[#126f77]">不止看起来像</p><h2 className="mt-2 text-2xl font-bold text-slate-900 sm:text-3xl">AI 是怎样帮你找到它的？</h2><p className="mt-3 text-sm leading-6 text-slate-500">系统理解照片与自然语言，再把四种线索放在一起判断，避免只靠图片造成的误认。</p></div><div className="mx-auto mt-10 grid max-w-4xl gap-3 sm:grid-cols-4">{[['视觉相似度','50%','杯型、颜色、材质'],['文字特征','25%','杯盖、贴纸、划痕'],['发现地点','15%','体育馆及周边区域'],['发现时间','10%','遗失时段前后']].map(([title, percent, caption], index) => <div key={title} className="relative rounded-2xl border border-slate-200 bg-white p-5 text-center shadow-sm"><div className="mx-auto grid size-12 place-items-center rounded-2xl bg-[#eaf6f3] text-lg font-bold text-[#126f77]">{percent}</div><h3 className="mt-3 text-sm font-bold text-slate-800">{title}</h3><p className="mt-1 text-xs leading-5 text-slate-400">{caption}</p>{index < 3 && <span className="absolute -right-3 top-1/2 z-10 hidden -translate-y-1/2 rounded-full bg-white p-1 text-slate-300 shadow-sm sm:block">+</span>}</div>)}</div><div className="mx-auto mt-6 flex max-w-4xl items-center justify-center gap-2 rounded-2xl bg-[#153f47] px-6 py-4 text-center text-sm font-medium text-white"><Sparkles className="size-4 text-[#8be0cf]" /> 多模态综合判断 → 白色保温杯，匹配度 94%</div></div></section>
      <footer className="bg-white py-8"><div className="mx-auto flex max-w-7xl flex-col items-center justify-between gap-4 px-5 text-xs text-slate-400 sm:flex-row sm:px-8"><div className="flex items-center gap-2 font-semibold text-slate-600"><Sparkles className="size-4 text-[#126f77]" /> 拾光 · 让每一件遗失都被看见</div><div className="flex items-center gap-1.5"><ShieldCheck className="size-4" /> 物品敏感细节仅用于领取验证，不公开展示</div></div></footer>

      <Dialog open={claimOpen} onOpenChange={(open) => { setClaimOpen(open); if (!open) setClaimed(false); }}><DialogContent className="max-w-md rounded-3xl p-6"><DialogHeader><div className="mb-2 grid size-12 place-items-center rounded-2xl bg-[#e9f7f2] text-[#14786e]"><ShieldCheck className="size-6" /></div><DialogTitle className="text-xl">领取前，验证一个小细节</DialogTitle><DialogDescription className="leading-6">为了避免冒领，请描述一项照片和页面上没有公开的细节。系统只在当前页面完成演示验证，无须提交给任何人。</DialogDescription></DialogHeader>{!claimed ? <Textarea className="min-h-24 rounded-xl" placeholder="例如：杯底写了什么？里面是否还有物品？" /> : <div className="flex items-start gap-3 rounded-2xl bg-emerald-50 p-4 text-sm text-emerald-700"><span className="grid size-8 shrink-0 place-items-center rounded-full bg-emerald-600 text-white"><Check className="size-4" /></span><span><strong className="block text-emerald-900">本地验证已完成</strong><span className="mt-1 block">请携带校园卡前往体育馆失物招领处领取。</span></span></div>}<DialogFooter className="-mx-6 -mb-6 px-6">{claimed ? <Button onClick={() => setClaimOpen(false)} className="h-10 rounded-xl bg-[#126f77] px-5">知道了</Button> : <Button onClick={() => setClaimed(true)} className="h-10 rounded-xl bg-[#126f77] px-5">立即验证</Button>}</DialogFooter></DialogContent></Dialog>
      <Dialog open={reportOpen} onOpenChange={(open) => { setReportOpen(open); if (!open) setRecognized(false); }}><DialogContent className="max-w-lg rounded-3xl p-6"><DialogHeader><DialogTitle className="text-xl">拍照，剩下的交给 AI</DialogTitle><DialogDescription>上传物品照片后，AI 会自动识别类别、颜色、材质和明显特征。</DialogDescription></DialogHeader>{!recognized ? <label className="group grid min-h-52 cursor-pointer place-items-center rounded-2xl border-2 border-dashed border-[#a9d0c8] bg-[#f3faf8] p-6 text-center transition hover:bg-[#eaf6f3]"><span><span className="mx-auto grid size-14 place-items-center rounded-2xl bg-white text-[#126f77] shadow-sm"><Upload className="size-6" /></span><span className="mt-4 block text-sm font-bold text-slate-800">拍照或上传图片</span><span className="mt-1 block text-xs text-slate-400">支持 JPG、PNG，照片越清晰识别越准确</span></span><input type="file" accept="image/*" capture="environment" className="sr-only" onChange={(e) => e.target.files?.[0] && window.setTimeout(() => setRecognized(true), 450)} /></label> : <div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><div className="flex items-center gap-2 text-sm font-bold text-emerald-800"><Sparkles className="size-4" /> AI 已完成识别</div><dl className="mt-4 grid grid-cols-[76px_1fr] gap-y-2 text-sm"><dt className="text-slate-400">物品</dt><dd className="font-medium">保温杯</dd><dt className="text-slate-400">颜色</dt><dd className="font-medium">白色</dd><dt className="text-slate-400">特征</dt><dd className="font-medium">蓝色杯盖、杯身有卡通贴纸</dd><dt className="text-slate-400">发现地点</dt><dd className="font-medium">体育馆</dd></dl><Button onClick={() => { setReportOpen(false); showNotice('失物已成功登记'); }} className="mt-5 h-10 w-full rounded-xl bg-[#126f77]">确认并发布</Button></div>}<div className="grid grid-cols-3 gap-2 text-center text-xs text-slate-500">{['自动识别物品','提取明显特征','确认后一键发布'].map((text, index) => <div key={text} className="rounded-xl bg-slate-50 p-3"><span className="mb-1 block font-bold text-[#126f77]">0{index + 1}</span>{text}</div>)}</div></DialogContent></Dialog>
      {notice && <div role="status" className="fixed bottom-6 left-1/2 z-[100] -translate-x-1/2 rounded-full bg-slate-900 px-5 py-3 text-sm font-medium text-white shadow-2xl">{notice}</div>}
    </main>
  );
}
